repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.62.0
    hooks:
      - id: golangci-lint
        args:
          - --config=.golangci.yml
        entry: golangci-lint run --fix
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-test
        name: go test
        entry: go test -v ./...
        language: system
        pass_filenames: false
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
