FROM python:3.10-slim

# use aliyun mirror
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources \
    && sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources
RUN apt-get clean && apt-get update 
RUN apt-get install -y pkg-config libseccomp-dev wget xz-utils
# copy main binary to /main
COPY main /main
COPY conf/config.yaml /conf/config.yaml
RUN rm -rf /var/lib/apt/lists/* \
    && chmod +x /main \
    && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple jinja2 requests httpx numpy \
    && wget -O /opt/node-v20.11.1-linux-arm64.tar.xz https://npmmirror.com/mirrors/node/v20.11.1/node-v20.11.1-linux-arm64.tar.xz \
    && tar -xvf /opt/node-v20.11.1-linux-arm64.tar.xz -C /opt \
    && ln -s /opt/node-v20.11.1-linux-arm64/bin/node /usr/local/bin/node \
    && rm -f /opt/node-v20.11.1-linux-arm64.tar.xz

ENTRYPOINT ["/main"]