FROM python:3.10-slim

# copy the source code into the container
COPY . /workdir

# install the necessary dependencies
RUN apt-get update && apt-get install -y \
    pkg-config gcc libseccomp-dev wget \
    && rm -rf /var/lib/apt/lists/*

# install Go
RUN wget https://go.dev/dl/go1.20.6.linux-arm64.tar.gz -O /opt/go1.20.6.linux-arm64.tar.gz \
    && tar zxf /opt/go1.20.6.linux-arm64.tar.gz -C /opt \
    && rm /opt/go1.20.6.linux-arm64.tar.gz \
    && ln -s /opt/go/bin/go /usr/local/bin/go

# install the necessary Go dependencies
RUN cd /workdir && go mod tidy \
    && bash ./build/build_arm64.sh

# install the necessary Python dependencies
RUN pip install httpx requests jinja2 && pip install --upgrade urllib3 requests

# Link /usr/local/bin/python3 to /usr/bin/python3
RUN ln -s /usr/local/bin/python3 /usr/bin/python3

# run tests
RUN cd /workdir && go test -v github.com/langgenius/dify-sandbox/tests/integration_tests/...
