FROM docker.1ms.run/python:3.10-slim-bookworm

# copy main binary to /main
COPY main /main
COPY volumes/sandbox/conf/config.yaml /conf/config.yaml
COPY volumes/sandbox/dependencies/python-requirements.txt /dependencies/python-requirements.txt

# 创建目录
RUN mkdir -p /opt

# 安装Python依赖
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /dependencies/python-requirements.txt \
    && chmod +x /main

# 尝试不使用预安装工具而通过下载一个curl二进制来安装Node.js
RUN cd /tmp \
    && python3 -c "import urllib.request; urllib.request.urlretrieve('https://registry.npmmirror.com/-/binary/node/v20.11.1/node-v20.11.1-linux-x64.tar.xz', 'node.tar.xz')" \
    && mkdir -p /opt/node \
    && python3 -c "import tarfile; tarfile.open('node.tar.xz').extractall('/opt')" \
    && ln -s /opt/node-v20.11.1-linux-x64/bin/node /usr/local/bin/node \
    && ln -s /opt/node-v20.11.1-linux-x64/bin/npm /usr/local/bin/npm \
    && npm config set registry https://registry.npmmirror.com \
    && npm install -g lodash@4.17.21 dayjs@1.11.10 \
    && rm -f /tmp/node.tar.xz

ENTRYPOINT ["/main"]